name: Block branch creation

on:
  create:
    branches:
      - '*'

jobs:
  block-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch creator
        run: |
          echo "Branch ${{ github.ref }} was created by ${{ github.actor }}"

      - name: Delete unauthorized branch
        if: github.actor != 'Mario-228'
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          curl -X DELETE \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME
